# Generated by Django 3.2.8 on 2021-10-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=510),
        ),
    ]
