# Generated by Django 3.2.8 on 2021-10-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
