# Generated by Django 3.2.8 on 2021-10-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_company_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='company',
        ),
    ]
