# Generated by Django 3.2.8 on 2021-10-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211011_0849'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AddField(
            model_name='customuser',
            name='emissions_CO2e',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
    ]
