# Generated by Django 3.2.8 on 2021-10-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('start_address', models.CharField(max_length=255)),
                ('end_address', models.CharField(max_length=255)),
                ('vehicle_registration', models.CharField(max_length=17)),
                ('emissions_CO2e', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
            ],
        ),
    ]
