# Generated by Django 3.2.8 on 2021-10-13 09:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('start_address', models.CharField(max_length=255)),
                ('end_address', models.CharField(max_length=255)),
                ('distance_km', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('coords', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=10, max_digits=19), size=None)),
                ('dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(auto_now=True), size=None)),
                ('vehicle_registration', models.CharField(max_length=17, null=True)),
                ('vehicle_class', models.CharField(max_length=17, null=True)),
                ('vehicle_emissions_CO2e_km', models.IntegerField(default=0)),
            ],
        ),
    ]
