# Generated by Django 3.2.8 on 2021-10-12 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='emissions_CO2e',
        ),
        migrations.AddField(
            model_name='route',
            name='distance_km',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='route',
            name='vehicle_emissions_CO2e_km',
            field=models.CharField(default=django.utils.timezone.now, max_length=17),
            preserve_default=False,
        ),
    ]
