# Generated by Django 3.2.8 on 2021-10-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='emissions',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
    ]
