# Generated by Django 3.2.8 on 2021-10-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='vehicle_class',
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='vehicle_registration',
            field=models.CharField(max_length=17, null=True),
        ),
    ]
