# Generated by Django 3.2.8 on 2021-10-12 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20211012_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='vehicle_emissions_CO2e_km',
        ),
    ]
