# Generated by Django 3.2.8 on 2021-10-14 18:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_route_emissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='coords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=20, max_digits=40), size=None),
        ),
        migrations.AlterField(
            model_name='route',
            name='distance_km',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='route',
            name='emissions',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='route',
            name='vehicle_emissions_CO2e_km',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=40),
        ),
    ]
