# Generated by Django 3.2.8 on 2021-10-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_remove_route_vehicle_emissions_co2e_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='vehicle_emissions_CO2e_km',
            field=models.IntegerField(default=0),
        ),
    ]
